# -------------------------------------------
# File: .github/workflows/ai_review.yml
# -------------------------------------------
name: LangGraph AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

name: LangGraph AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r langgraph_agent/requirements.txt
          pip install -r web_dashboard/requirements.txt
          pip install python-dotenv
          pip install .

      - name: Debug ENV
        run: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "PR_NUMBER=${PR_NUMBER}"

      - name: Run LangGraph AI Reviewer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: ai-review
